---
title: "**Schedule and Slides** "
subtitle: "Data Science and AI, Fall 2025"
#date: "`r Sys.Date()`"
#author: "曲兆鹏"
#institute: "南京大学"
output:
  prettydoc::html_pretty:
    theme: leonids
    highlight: github
---

```{=html}
<style type="text/css">
  body{
  font-size: 14pt;
}
</style>
```

| Week | Date | Topic | Slides |
|:----------------:|:-----------------|:-----------------|:-----------------:|
| 1 | 8/28 | Introduction to course content, Data Science, AI and Economics, Introduction to basic data analysis process |  |
| 2 | 9/4  | Introduction to Git and GitHub  |  |
| 3 | 9/11 | Introduction to VsCode, IDEs, and basic AI tools(Copilot) |  | 
| 4 | 9/18 | Introduction to R and Python | \[Lec1\] |
| 5 | 9/25 | Introduction to API(I) | \[Lec2\] |
| 6 | 10/2 | National Day |  |
| 7 | 10/9 | Introduction to API(II)
| 7 | 10/17  | Introduction to spatial data and GIS analysis: Using NASA night light data as an example | \[Lec4\] |
| 8 | 10/24  | Introduction to spatial data and GIS analysis: Using NASA night light data as an example | \[Lec5\]) |
| 9 | 10/31  | Research Project Proposal Presentations | Students Presentations |
| 10 | 11/7  | OCR and text recognition: Based on Baidu PaddlePaddle platforms |  |
| 11 | 11/14 | OCR and text recognition: Based on Baidu PaddlePaddle platform |  |
| 12 | 11/21 | Web scraping: Based on Baidu search (or Sina Weibo) | \[Lec6\] |
| 13 | 11/28 | Web scraping: Based on Baidu search (or Sina Weibo) | \[Lec7\] |
| 14 | 12/5   | Text as Data|  |
| 15 | 12/12 | Text as Data |  |
| 16 | 12/19  |  Introduction to Big Data |  |
| 17 | 12/26 | Research Project Report Presentations | Students Presentations |