---
title: "**Schedule and Slides** "
subtitle: "Data Science and AI, Fall 2025"
#date: "`r Sys.Date()`"
#author: "曲兆鹏"
#institute: "南京大学"
output:
  prettydoc::html_pretty:
    theme: leonids
    highlight: github
---

```{=html}
<style type="text/css">
  body{
  font-size: 14pt;
}
</style>
```

| Week | Date | Topic | Slides | Labs |
|:-------------:|:--------------|:--------------|:-------------:|:-------------:|
| 1 | 8/28 | Introduction to course content, Data Science, AI and Economics, Introduction to basic data analysis process | [Lec0](/slides/DSAI_Lec0_2025.pdf) |  |
| 2 | 9/4 | Introduction to Git and GitHub | [Lec1](/slides/DSAI_Lec1_2025.pdf) | [Lab1A](/slides/DSAI_Lab1A_2025.pdf) [Lab1B](/slides/DSAI_Lab1B_2025.pdf) |
| 3 | 9/11 | Introduction to R, Rmardown, Git and GitHub(Continued) | [Lec2](/slides/DSAI_Lec2_2025.pdf) |  |
| 4 | 9/18 | Introduction to spatial data and GIS analysis: Using NASA night light data as an example | [Lec3](/slides/DSAI_Lec3_2025.pdf) | [Lab3](/labs/Lab3_GIS.R) [Data](/data/Shapes.zip) |
| 5 | 9/25 | Introduction to spatial data and GIS analysis: Using NASA night light data as an example | [Lec4](/slides/DSAI_Lec4_2025.pdf) | [Lab4](/labs/Lab4_NTL.R) [Data](/data/Shapes.zip) |
| 6 | 10/2 | National Day |  |  |
| 7 | 10/9 | Introduction to VS Code, R and Github | [Lec5](/slides/DSAI_Lec5_2025.pdf) |  |
| 8 | 10/16 | Introduction to VS Code and Python | [Lec6](/slides/DSAI_Lec6_2025.pdf) |  |
| 9 | 10/23 | Introduction to AI tools(Copilot) to Coding | [Lec7](/slides/DSAI_Lec7_2025.pdf) |  |
| 10 | 10/31 | OCR and text recognition: Based on Baidu PaddlePaddle platforms | [Lec8](/slides/DSAI_Lec7_2025.pdf) |  |
| 11 | 11/7 | OCR and text recognition: Based on Baidu PaddlePaddle platform |  |  |
| 12 | 11/14 | Web scraping: Based on Baidu search (or Sina Weibo) |  |  |
| 13 | 11/21 | Web scraping: Based on Baidu search (or Sina Weibo) |  |  |
| 10 | 11/28 | Research Project Proposal Presentations | Students Presentations |  |
| 14 | 12/5 | Text as Data |  |  |
| 15 | 12/12 | Text as Data |  |  |
| 16 | 12/19 | Introduction to Big Data |  |  |
| 17 | 12/26 | Research Project Report Presentations | Students Presentations |  |