---
title: "**Syllabus(课程计划)** "
subtitle: "DS & AI for Economists,Fall 2025"
# author: "Instructor:曲兆鹏;TA:王紫澍"
# institute: "南京大学"
output:
  prettydoc::html_pretty:
    theme: leonids
    highlight: github
---

```{=html}
<style type="text/css">
  body{
  font-size: 13pt;
}
</style>
```

### Course Description

This course is designed to teach students how to use the latest knowledge and tools in data science and artificial intelligence to enhance their ability to analyze economic and social big data.

Through specific application cases, students will gain an introductory understanding of basic tools in artificial intelligence and data science, and apply these tools in areas such as spatial data analysis, web scraping and text analysis, OCR and text recognition, and machine learning applications. Unlike traditional econometrics courses or machine learning courses, this course does not focus on the theory behind various algorithms or methods. Instead, it centers on fundamental knowledge and tools in data science and artificial intelligence, using real-world cases and project-based tasks to develop students' ability to acquire, process, and utilize non-traditional economic data. The goal is to enhance students' competitiveness in economic research in the digital age.

At the end, students will use the to finish an empirical research projects with big data based on the knowledge and tools learned in this course.

### Evaluation

-   Participation（$10\%$）

-   Proposal Presentations for Group Projects ($50\%$)

-   Preliminary results for Group Projects ($40\%$)

### Textbooks

-   The course have no required textbooks, but the following books and online resources are recommended for further reading and reference:

-   Hadley Wickham and Garrett Grolemund, [*R for Data Science:Second edition*](https://r4ds.hadley.nz),O'Reilly Media, 2023.

-   Gareth James, Daniela Witten, Trevor Hastie and Robert Tibshirani, [*An Introduction to Statistical Learning: with Applications in R: Second edition*](https://hastie.su.domains/ISLR2/ISLRv2_corrected_June_2023.pdf.download.html), Springer, 2023.

-   Immanuel Trummer, [*Data Analysis with LLMs: Texts,tables,images and sound*](https://www.oreilly.com/library/view/data-analysis-with/9781633437647/), O'Reilly Media, 2025.